name: build

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Build      
        env:
          API_KEY: ${{ secrets.API_KEY }}
         
        run: |
          echo '{  "API_KEY": "${ env:API_KEY }" }'
