name: build

env:
  # Setting an environment variable with the value of a configuration variable
  api_key: ${{ vars.API_KEY2 }}
  
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Build      
           
        run: |
          keys='{ "API_KEY2": "'
          keys+="$api_key"
          keys+='" }'
          # echo "${{ secrets.API_KEY }}"
          # echo "${{ vars.API_KEY2 }}"
          echo $keys
