name: build

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Build      
           
        run: |
          echo "${{ secrets.API_KEY }}"
          echo "${{ vars.API_KEY2 }}"
          # echo "${{ env.API_KEY2 }}"
          # echo '{  "API_KEY": "${ env:API_KEY }", "API_KEY2": "${ env:API_KEY2 }" }'
