name: build

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Build      
           
        run: |
          keys='{ "API_KEY2": "'
          keys+="$vars.API_KEY2"
          keys+='" }'

          echo $keys
